#!/bin/bash

if [[ $1 == 'true' ]] ; then
  #Remove d2js
  rm -r src/vendor/d2js/
  rm -r build/vendor/d2js/

  #Run bower install to get d2js
  bower install
fi

if [[ $1 == 'dev' ]] ; then
  cp -r ../apps/d2js/dist/* src/vendor/d2js/dist
fi

gulp build

#Overwrite the webapp with the fake one for faster testing
cp src/main/_manifest.webapp build/manifest.webapp

gulp deploy
gulp copy-fake-api
